name: Streaming list update

on: 
  push:
    # 모든 브랜치 푸시에 대해 실행
  schedule:
    # 🚨 수정: 매 시간 00분에 실행되도록 변경
    - cron: '0 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
      
    - name: gensh-unittest result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
      
    - name: Commit files
      run: |
        echo "현재 Ref: ${{ github.ref }}"
        
        # 1. 파일 다운로드 (공개 저장소)
        WGET_URL="https://raw.githubusercontent.com/alexcha/test1/main/check.sh"
        echo "다운로드 시도 URL: $WGET_URL"
        
        wget "$WGET_URL" -O check.sh || { 
          echo "🚨🚨🚨 ERROR: 파일 다운로드 실패. URL을 확인하세요. 🚨🚨🚨"
          exit 1
        }
        
        # 2. 스크립트 실행 환경 설정 및 의존성 설치
        export LANG=ko_KR.UTF-8
        # 🚨 sudo를 사용하여 권한 오류 해결
        sudo apt-get -y update
        sudo apt-get -y install html2text
        
        chmod +x check.sh
        
        # 3. 스크립트 실행 및 결과 파일 생성
        ./check.sh > result.txt

        # 4. Git 설정 및 커밋
        git add result.txt
        
        git config --global user.email test@local
        git config --global user.name test

        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: new data commit"
          git branch -M main
          
          # 5. git push: 기본 인증을 사용하여 현재 저장소에 푸시
          git push
        fi
        
    - name: Push changes
      # 이전 스텝에서 이미 푸시했으므로 비활성화
      if: false 
      uses: ad-m/github-push-action@v5 
      with:
        github_token: ${{ secrets.ETC_KEY }}
