name: Streaming list update

on: 
  push:
  schedule:
    - cron: '5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
      
    - name: gensh-unittest result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
      
    - name: Commit files
      run: |
        echo "현재 Ref: ${{ github.ref }}"
        
        # 1. 파일 다운로드 
        WGET_URL="https://raw.githubusercontent.com/alexcha/test1/main/check.sh"
        echo "다운로드 시도 URL: $WGET_URL"
        
        wget "$WGET_URL" -O check.sh || { 
          echo "🚨🚨🚨 ERROR: 파일 다운로드 실패. URL을 확인하세요. 🚨🚨🚨"
          exit 1
        }
        
        # 2. 스크립트 실행 환경 설정 및 의존성 설치
        export LANG=ko_KR.UTF-8
        #sudo apt-get -y update
        sudo apt-get -y install html2text
        
        chmod +x check.sh
        
        # 3. 스크립트 실행 및 결과 파일 생성
        ./check.sh >> result.txt

        # 4. Git 설정 및 커밋
        git add result.txt
        
        git config --global user.email test@local
        git config --global user.name test

        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: new data commit"
          git branch -M main
          
          # 5. git push는 기본 인증을 사용하여 수행
          git push
        fi
        
    - name: Push changes
      # 이 스텝은 'Commit files'에서 이미 푸시했으므로 비활성화하는 것을 권장합니다.
      if: false 
      # 🚨🚨🚨 수정: v4 대신 안정적인 master 브랜치를 다시 사용합니다. 🚨🚨🚨
      uses: ad-m/github-push-action@master 
      with:
        github_token: ${{ secrets.ETC_KEY }}
