name: Streaming list update

on: 
  push:
    # 모든 브랜치 푸시에 대해 실행
  schedule:
    # 2시간 30분마다 실행 (UTC 기준)
    - cron: '30 */2 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
      
    - name: gensh-unittest result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
      
    - name: Commit files
      # 1. secrets.ETC_KEY를 환경 변수 GITHUB_PAT로 설정
      env:
        GITHUB_PAT: ${{ secrets.ETC_KEY }}
      run: |
        echo "현재 Ref: ${{ github.ref }}"
        
        # 2. wget 명령어에 Authorization 헤더를 추가하여 비공개 파일 인증 후 다운로드
        # GITHUB_PAT 변수를 사용하여 secrets.ETC_KEY의 값을 토큰으로 전달
        wget --header="Authorization: token $GITHUB_PAT" \
             https://raw.githubusercontent.com/alexcha/test1/refs/heads/main/check.sh
        
        # 3. 스크립트 실행 환경 설정 및 의존성 설치
        export LANG=ko_KR.UTF-8  # 한글 깨짐 방지를 위해 인코딩 설정
        apt-get -y update
        apt-get -y install html2text
        chmod +x check.sh
        
        # 4. 스크립트 실행 및 결과 파일 생성
        ./check.sh > result.txt

        # 5. Git 설정 및 커밋
        git add result.txt
        
        git config --global user.email test@local
        git config --global user.name test

        # 변경 사항이 있을 때만 커밋하도록 조건 추가 (선택 사항)
        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: new data commit"
          git branch -M main
          # git push는 exit 0을 붙이면 안 됩니다. 성공/실패 코드가 파이프라인에 전달되어야 합니다.
          git push origin main
        fi
        
    - name: Push changes
      # 이 스텝은 'git push'를 이미 위에서 수동으로 했으므로,
      # 주석 처리하거나 삭제하는 것이 좋습니다.
      # 만약 이 스텝을 사용하려면, 위 Commit files 스텝에서 'git push'를 제거해야 합니다.
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        # 이미 위에서 git push를 했으므로 여기서는 토큰을 사용하지 않도록 합니다.
        # 이 스텝을 사용하는 경우, Commit files 스텝의 git push를 제거하세요.
        github_token: ${{ secrets.ETC_KEY }}
