name: Streaming list update

on: 
  push:
  schedule:
    - cron: '30 */2 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
      
    - name: gensh-unittest result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
      
    - name: Commit files
      # 비공개 저장소 인증이 필요 없으므로 env: GITHUB_PAT 설정 제거
      run: |
        echo "현재 Ref: ${{ github.ref }}"
        
        # 1. wget 명령으로 파일 다운로드 (인증 헤더 제거)
        WGET_URL="https://raw.githubusercontent.com/alexcha/test1/main/check.sh"
        echo "다운로드 시도 URL: $WGET_URL"
        
        # 공개 저장소이므로 일반 wget 사용
        wget "$WGET_URL" -O check.sh || { 
          echo "🚨🚨🚨 ERROR: 파일 다운로드 실패. URL을 확인하세요. 🚨🚨🚨"
          exit 1
        }
        
        # 2. 스크립트 실행 환경 설정 및 의존성 설치
        export LANG=ko_KR.UTF-8
        apt-get -y update
        apt-get -y install html2text
        chmod +x check.sh
        
        # 3. 스크립트 실행 및 결과 파일 생성
        ./check.sh > result.txt

        # 4. Git 설정 및 커밋
        git add result.txt
        
        # git config는 github.token 사용을 위해 변경하지 않는 것이 좋습니다.
        git config --global user.email test@local
        git config --global user.name test

        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Automated update: new data commit"
          git branch -M main
          
          # 5. git push는 기본 ${{ secrets.GITHUB_TOKEN }}을 사용하여 수행 (ETC_KEY 필요 없음)
          git push
        fi
        
    - name: Push changes
      # 이 스텝은 위의 'git push'로 대체되었습니다. 사용하지 않는 것을 권장합니다.
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        # 이 토큰은 'git push'에 사용되므로, ${{ secrets.GITHUB_TOKEN }} 또는 ${{ secrets.ETC_KEY }} 중
        # 푸시 권한이 있는 토큰을 사용해야 합니다.
        github_token: ${{ secrets.ETC_KEY }}
