name: Streaming list update

on: 
  push:
  schedule:
    # 매 시간 5분에 실행되도록 설정
    - cron: '5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
      
    - name: Get Unittest Result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
      
    - name: Commit files and Generate Chart (FINAL FIX)
      run: |
        echo "현재 Ref: ${{ github.ref }}"
        
        # 1. 파일 다운로드 및 환경 설정
        WGET_URL="https://raw.githubusercontent.com/alexcha/test1/main/check.sh"
        echo "다운로드 시도 URL: $WGET_URL"
        wget "$WGET_URL" -O check.sh || { echo "ERROR: File download failed." >&2; exit 1; }
        
        export LANG=ko_KR.UTF-8
        sudo apt-get -y update
        sudo apt-get -y install html2text
        
        chmod +x check.sh
        ./check.sh >> result.txt
        
        # ----------------------------------------------------
        # 2. 차트 생성 로직 시작
        # ----------------------------------------------------
        
        # 데이터 파싱 및 JavaScript 배열 포맷으로 변환 (JS_DATA)
        # 🚨 AWK 명령을 한 줄로 압축하여 YAML 충돌 위험 최소화
        JS_DATA=$(awk -F ' : ' '{ gsub(/,/, "", $2); if (NR==1) {printf "{"} else {printf ", "}; printf "x: \"%s\", y: %s}", $1, $2 }' result.txt)

        # HTML 파일 생성 (마커를 'EOF'로 단순화하고, Bash 변수 확장을 허용)
        # 64번째 줄 오류가 발생하지 않도록 이 구문을 최대한 간결하게 유지합니다.
        cat << CHART_END > chart.html
<!DOCTYPE html>
<html>
<head>
    <title>스트리밍 목록 업데이트 차트</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.1/dist/chartjs-adapter-moment.min.js"></script>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        #chartContainer { width: 90%; max-width: 1000px; margin: auto; }
    </style>
</head>
<body>
    <h1>스트리밍 데이터 변화 추이 (KST)</h1>
    <p>최근 업데이트 시간: $(tail -n 1 result.txt | awk -F ' : ' '{print $1}')</p>
    <div id="chartContainer">
        <canvas id="timeSeriesChart"></canvas>
    </div>
    
    <script>
    // JS_DATA를 직접 삽입하고, 외부에서 배열 괄호([])를 추가
    const chartData = [${JS_DATA}]; 

    const ctx = document.getElementById('timeSeriesChart').getContext('2d');
    
    new Chart(ctx, {
        type: 'line',
        data: {
            datasets: [{
                label: '값 변화 추이',
                data: chartData,
                borderColor: 'rgba(54, 162, 235, 1)',
                backgroundColor: 'rgba(54, 162, 235, 0.2)',
                borderWidth: 2,
                tension: 0.1,
                pointRadius: 3
            }]
        },
        options: {
            responsive: true,
            scales: {
                x: {
                    type: 'time',
                    adapters: {
                        date: {
                            zone: 'Asia/Seoul'
                        }
                    },
                    time: {
                        unit: 'hour',
                        tooltipFormat: 'yyyy-MM-dd HH:mm:ss KST',
                        displayFormats: {
                            hour: 'MM/DD HH:mm',
                            day: 'MM/DD'
                        }
                    },
                    title: { display: true, text: '시간' }
                },
                y: {
                    title: { display: true, text: '값' },
                    beginAtZero: false,
                    ticks: {
                        callback: function(value) {
                            return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                        }
                    }
                }
            },
            plugins: {
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            let label = context.dataset.label || '';
                            if (label) {
                                label += ': ';
                            }
                            if (context.parsed.y !== null) {
                                label += context.parsed.y.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                            }
                            return label;
                        }
                    }
                }
            }
        }
    });
    </script>
</body>
</html>
CHART_END # 🚨 들여쓰기 없음

        # ----------------------------------------------------
        # 3. 디버깅 및 Git 커밋
        # ----------------------------------------------------

        echo "--- File Status Check ---"
        if [ -f chart.html ]; then
            echo "chart.html successfully created. Size:"
            ls -lh chart.html
        else
            echo "🚨 FATAL ERROR: chart.html was NOT created!" >&2
            exit 1
        fi
        echo "-------------------------"

        # Git 커밋 및 푸시
        git add result.txt chart.html
        
        git config --global user.email test@local
        git config --global user.name test

        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          echo "Committing changes..."
          git commit -m "Automated update: data and chart"
          git branch -M main
          git push
        fi
        
    - name: Push changes
      if: false 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ETC_KEY }}
