name: Streaming list update

on: 
  push:
  schedule:
    - cron: '5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      
    - name: Github Action gen-sh-unittest
      id: action-gen-sh-unittest
      uses: vargiuscuola/gen-sh-unittest@master
      
    - name: Get Unittest Result
      run: echo "The result of gensh-unittest Action was ${{ steps.action-gen-sh-unittest.outputs.result }}"
      
    - name: Run Script, Generate Chart, and Commit
      run: |
        echo "--- 워크플로우 시작: README.md 생성 반영 ---"
        
        # 1. 상수 정의
        WGET_CHECK_URL="https://raw.githubusercontent.com/alexcha/test1/refs/heads/main/check.sh"
        WGET_CHART_URL="https://raw.githubusercontent.com/alexcha/test1/refs/heads/main/generate_chart.sh"
        WGET_RESULT_URL="https://raw.githubusercontent.com/alexcha/test1/refs/heads/main/result.txt"

        # 2. 필수 패키지 설치
        sudo apt-get -y update
        sudo apt-get -y install html2text # 이젠 필요 없지만 혹시 몰라 유지

        # 3. result.txt 다운로드
        echo "3. 기존 result.txt 다운로드 시도..."
        wget "$WGET_RESULT_URL" -O result.txt || echo "result.txt not found, starting fresh."
        
        # 4. check.sh 및 generate_chart.sh 다운로드
        echo "4. check.sh 및 generate_chart.sh 다운로드..."
        wget "$WGET_CHECK_URL" -O check.sh || { echo "ERROR: check.sh 다운로드 실패" >&2; exit 1; }
        wget "$WGET_CHART_URL" -O generate_chart.sh || { echo "ERROR: generate_chart.sh 다운로드 실패" >&2; exit 1; }

        # 5. 실행 권한 부여
        chmod +x check.sh generate_chart.sh
        
        # 6. check.sh 실행 및 result.txt에 데이터 추가
        echo "6. check.sh 실행 및 result.txt에 새로운 데이터 추가..."
        ./check.sh >> result.txt
        
        # 7. generate_chart.sh 실행 (README.md 생성)
        echo "7. generate_chart.sh 실행 및 README.md 생성..."
        ./generate_chart.sh
        
        # 8. 생성 파일 확인 (디버깅)
        echo "--- File Status Check ---"
        if [ -f README.md ]; then # 🚨 파일 이름 변경
            echo "README.md이 성공적으로 생성되었습니다. 크기:"
            ls -lh README.md
        else
            echo "🚨 FATAL ERROR: README.md 생성이 실패했습니다!" >&2
            exit 1
        fi
        echo "-------------------------"

        # 9. Git 커밋 및 푸시
        echo "9. Git 커밋 및 푸시..."
        # 🚨 chart.html 대신 README.md 추가
        git add result.txt README.md
        
        git config --global user.email test@local
        git config --global user.name test

        if git diff --cached --exit-code; then
          echo "No changes to commit."
        else
          echo "Committing changes..."
          git commit -m "Automated update: data and README.md (data table)"
          git branch -M main
          git push
        fi
        
    - name: Push changes
      if: false 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ETC_KEY }}
